[2025-08-18T13:07:55.266+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T13:07:55.478+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_04_problem_types manual__2025-08-18T13:01:28.400079+00:00 [queued]>
[2025-08-18T13:07:55.554+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_04_problem_types manual__2025-08-18T13:01:28.400079+00:00 [queued]>
[2025-08-18T13:07:55.559+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T13:07:55.829+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): run_q_04_problem_types> on 2025-08-18 13:01:28.400079+00:00
[2025-08-18T13:07:55.849+0000] {standard_task_runner.py:63} INFO - Started process 4640 to run task
[2025-08-18T13:07:55.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_04_problem_types', 'manual__2025-08-18T13:01:28.400079+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpogpim8gm']
[2025-08-18T13:07:55.890+0000] {standard_task_runner.py:91} INFO - Job 255: Subtask run_q_04_problem_types
[2025-08-18T13:07:56.168+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_04_problem_types manual__2025-08-18T13:01:28.400079+00:00 [running]> on host 47205959681c
[2025-08-18T13:07:56.501+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'run_q_04_problem_types', field 'sql'. Template: '/opt/***/sql/q_04_problem_types.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/q_04_problem_types.sql
[2025-08-18T13:07:56.504+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2476, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2629, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3079, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.9/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/q_04_problem_types.sql
[2025-08-18T13:07:56.517+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_04_problem_types, execution_date=20250818T130128, start_date=20250818T130755, end_date=20250818T130756
[2025-08-18T13:07:56.543+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 255 for task run_q_04_problem_types (/opt/airflow/sql/q_04_problem_types.sql; 4640)
[2025-08-18T13:07:56.588+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T13:07:56.662+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-08-18T13:07:56.706+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T13:07:56.715+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
