[2025-08-18T18:31:08.112+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T18:31:08.271+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_06_magic_tags manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:31:08.319+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.run_q_06_magic_tags manual__2025-08-18T18:24:04.884207+00:00 [queued]>
[2025-08-18T18:31:08.319+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T18:31:08.401+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_q_06_magic_tags> on 2025-08-18 18:24:04.884207+00:00
[2025-08-18T18:31:08.412+0000] {standard_task_runner.py:63} INFO - Started process 10766 to run task
[2025-08-18T18:31:08.426+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'run_q_06_magic_tags', 'manual__2025-08-18T18:24:04.884207+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpzynl5k9f']
[2025-08-18T18:31:08.443+0000] {standard_task_runner.py:91} INFO - Job 481: Subtask run_q_06_magic_tags
[2025-08-18T18:31:08.816+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.run_q_06_magic_tags manual__2025-08-18T18:24:04.884207+00:00 [running]> on host 47205959681c
[2025-08-18T18:31:09.593+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='run_q_06_magic_tags' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T18:24:04.884207+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T18:24:04.884207+00:00'
[2025-08-18T18:31:09.594+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T18:31:09.813+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T18:31:09.815+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'PGPASSWORD=citus psql -h citus_coordinator-U citus -d youtube_dw -f /opt/***/sql/q_06_magic_tags.sql']
[2025-08-18T18:31:09.869+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T18:31:10.146+0000] {subprocess.py:93} INFO - psql: error: could not translate host name "citus_coordinator-U" to address: Temporary failure in name resolution
[2025-08-18T18:31:10.153+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T18:31:10.155+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T18:31:10.192+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T18:31:10.217+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=run_q_06_magic_tags, execution_date=20250818T182404, start_date=20250818T183108, end_date=20250818T183110
[2025-08-18T18:31:10.656+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 481 for task run_q_06_magic_tags (Bash command failed. The command returned a non-zero exit code 2.; 10766)
[2025-08-18T18:31:10.744+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T18:31:10.942+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T18:31:10.960+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
