[2025-08-18T13:44:27.519+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T13:44:27.560+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.check_raw_files manual__2025-08-18T13:43:54.892480+00:00 [queued]>
[2025-08-18T13:44:27.571+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_pipeline_batch_data.check_raw_files manual__2025-08-18T13:43:54.892480+00:00 [queued]>
[2025-08-18T13:44:27.571+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-08-18T13:44:27.595+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): check_raw_files> on 2025-08-18 13:43:54.892480+00:00
[2025-08-18T13:44:27.602+0000] {standard_task_runner.py:63} INFO - Started process 5313 to run task
[2025-08-18T13:44:27.607+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_pipeline_batch_data', 'check_raw_files', 'manual__2025-08-18T13:43:54.892480+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/tmp/tmpae3y6l6k']
[2025-08-18T13:44:27.610+0000] {standard_task_runner.py:91} INFO - Job 340: Subtask check_raw_files
[2025-08-18T13:44:27.663+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_pipeline_batch_data.check_raw_files manual__2025-08-18T13:43:54.892480+00:00 [running]> on host 47205959681c
[2025-08-18T13:44:27.760+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_pipeline_batch_data' AIRFLOW_CTX_TASK_ID='check_raw_files' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T13:43:54.892480+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T13:43:54.892480+00:00'
[2025-08-18T13:44:27.761+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T13:44:27.779+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T13:44:27.780+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        if docker exec -it namenode hdfs dfs -test -e /storage/hdfs/raw/; then\n            echo "Found raw files"\n        else\n            echo "No raw files found, exiting" && exit 1\n        fi\n        ']
[2025-08-18T13:44:27.793+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T13:44:27.823+0000] {subprocess.py:93} INFO - the input device is not a TTY
[2025-08-18T13:44:27.825+0000] {subprocess.py:93} INFO - No raw files found, exiting
[2025-08-18T13:44:27.826+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-18T13:44:27.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T13:44:27.842+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-18T13:44:27.846+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_pipeline_batch_data, task_id=check_raw_files, execution_date=20250818T134354, start_date=20250818T134427, end_date=20250818T134427
[2025-08-18T13:44:27.866+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 340 for task check_raw_files (Bash command failed. The command returned a non-zero exit code 1.; 5313)
[2025-08-18T13:44:27.900+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T13:44:27.937+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T13:44:27.938+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
